for file in $HOME/.files/zsh/*aliases.zsh; do
	source "$file"
done

for binDirectory in $HOME/.files/*/bin; do
	PATH="$PATH:$binDirectory"
done

export PATH

export EDITOR=/usr/bin/vim
export VISUAL=vim
export LIBVA_DRIVER_NAME=iHD
